/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteEntregdorArgs } from "./DeleteEntregdorArgs";
import { EntregdorFindManyArgs } from "./EntregdorFindManyArgs";
import { EntregdorFindUniqueArgs } from "./EntregdorFindUniqueArgs";
import { Entregdor } from "./Entregdor";
import { EntregdorService } from "../entregdor.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Entregdor)
export class EntregdorResolverBase {
  constructor(
    protected readonly service: EntregdorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Entregdor",
    action: "read",
    possession: "any",
  })
  async _entregdorsMeta(
    @graphql.Args() args: EntregdorFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Entregdor])
  @nestAccessControl.UseRoles({
    resource: "Entregdor",
    action: "read",
    possession: "any",
  })
  async entregdors(
    @graphql.Args() args: EntregdorFindManyArgs
  ): Promise<Entregdor[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Entregdor, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Entregdor",
    action: "read",
    possession: "own",
  })
  async entregdor(
    @graphql.Args() args: EntregdorFindUniqueArgs
  ): Promise<Entregdor | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Entregdor)
  @nestAccessControl.UseRoles({
    resource: "Entregdor",
    action: "delete",
    possession: "any",
  })
  async deleteEntregdor(
    @graphql.Args() args: DeleteEntregdorArgs
  ): Promise<Entregdor | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
